import type { Product, Customer, Sale } from '../types';
import { v4 as uuidv4 } from 'uuid';
import { subDays } from 'date-fns';

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Eternal Heritage Mangalsutra',
    sku: 'AUR-MS-001',
    category: 'Necklace',
    metalType: 'Gold',
    purity: '22K',
    weight: 12.5,
    makingCharges: 4500,
    makingChargePercent: 0,
    isPercentageMakingCharge: false,
    stoneCharges: 2500,
    wastagePercent: 2,
    basePrice: 0,
    sellingPrice: 85000,
    stock: 10,
    lowStockThreshold: 2,
    barcode: '8901234567890',
    images: [],
    description: 'A traditional 22K gold Mangalsutra with fine black beads and meenakari work.',
    hsnCode: '71131910',
    isRateSensitive: true,
    isActive: true,
    stockType: 'Fine',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Royal Temple Necklace Set',
    sku: 'AUR-NC-004',
    category: 'Necklace',
    metalType: 'Gold',
    purity: '22K',
    weight: 48.5,
    makingCharges: 15000,
    makingChargePercent: 0,
    isPercentageMakingCharge: false,
    stoneCharges: 8500,
    wastagePercent: 3,
    basePrice: 0,
    sellingPrice: 325000,
    stock: 3,
    lowStockThreshold: 1,
    barcode: '8901234567891',
    images: [],
    description: 'Exquisite 22K temple jewellery necklace with Lakshmi motif and rubies.',
    hsnCode: '71131910',
    isRateSensitive: true,
    isActive: true,
    stockType: 'Fine',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'Kundan Polki Jhumkas',
    sku: 'AUR-ER-009',
    category: 'Earring',
    metalType: 'Gold',
    purity: '18K',
    weight: 18.2,
    makingCharges: 8500,
    makingChargePercent: 0,
    isPercentageMakingCharge: false,
    stoneCharges: 45000,
    wastagePercent: 1.5,
    basePrice: 0,
    sellingPrice: 155000,
    stock: 5,
    lowStockThreshold: 1,
    barcode: '8901234567892',
    images: [],
    description: 'Traditional heavy Kundan work Jhumkas with freshwater pearl drops.',
    hsnCode: '71131910',
    isRateSensitive: true,
    isActive: true,
    stockType: 'Fine',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    name: 'Classic Gold Kada Set',
    sku: 'AUR-BN-012',
    category: 'Bangles',
    metalType: 'Gold',
    purity: '22K',
    weight: 65.0,
    makingCharges: 12000,
    makingChargePercent: 0,
    isPercentageMakingCharge: false,
    stoneCharges: 0,
    wastagePercent: 2.5,
    basePrice: 0,
    sellingPrice: 420000,
    stock: 4,
    lowStockThreshold: 1,
    barcode: '8901234567893',
    images: [],
    description: 'Hard gold Kada with intricate hand-engraved patterns.',
    hsnCode: '71131910',
    isRateSensitive: true,
    isActive: true,
    stockType: 'Fine',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    name: 'Silver Payal (Traditional)',
    sku: 'AUR-AN-007',
    category: 'Anklet',
    metalType: 'Silver',
    purity: '925',
    weight: 120.0,
    makingCharges: 1800,
    makingChargePercent: 0,
    isPercentageMakingCharge: false,
    stoneCharges: 0,
    wastagePercent: 5,
    basePrice: 0,
    sellingPrice: 12500,
    stock: 20,
    lowStockThreshold: 5,
    barcode: '8901234567894',
    images: [],
    description: 'Heavy traditional silver Payal with tinkling bells.',
    hsnCode: '71131910',
    isRateSensitive: true,
    isActive: true,
    stockType: 'Fine',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Anjali Sharma',
    phone: '9820012345',
    email: 'anjali@example.com',
    address: 'B-402, Sea View Apartments, Worli, Mumbai',
    gstin: '',
    panNumber: 'ABCDE1234F',
    loyaltyPoints: 1250,
    totalPurchases: 2,
    totalSpent: 105000,
    totalPaid: 105000,
    outstandingBalance: 0,
    createdAt: subDays(new Date(), 45).toISOString(),
    notes: 'Prefers temple designs and antique finish.',
  },
  {
    id: 'cust-2',
    name: 'Vikram Malhotra',
    phone: '9810056789',
    email: 'vikram.m@gmail.com',
    address: 'Flat 12, Oberoi Towers, Goregaon East, Mumbai',
    gstin: '27AABCM1234P1Z1',
    panNumber: 'FGHIJ5678K',
    loyaltyPoints: 5400,
    totalPurchases: 1,
    totalSpent: 215000,
    totalPaid: 215000,
    outstandingBalance: 0,
    createdAt: subDays(new Date(), 20).toISOString(),
    notes: 'High value customer, looking for diamond investment.',
  },
  {
    id: 'cust-3',
    name: 'Priya Iyer',
    phone: '9870011223',
    email: 'priya.iyer@yahoo.com',
    address: '5th Floor, Sai Dham, Matunga, Mumbai',
    gstin: '',
    panNumber: '',
    loyaltyPoints: 850,
    totalPurchases: 3,
    totalSpent: 45000,
    totalPaid: 45000,
    outstandingBalance: 0,
    createdAt: subDays(new Date(), 60).toISOString(),
    notes: 'Interested in daily wear 18K gold collection.',
  },
];

export const SEED_SALES: Sale[] = [
  {
    id: uuidv4(),
    invoiceNumber: 'INV-2024-0001',
    customerId: 'cust-1',
    customerName: 'Anjali Sharma',
    customerPhone: '9820012345',
    items: [
      {
        product: SEED_PRODUCTS[0],
        quantity: 1,
        discountPercent: 0,
        discountAmount: 0,
        finalPrice: SEED_PRODUCTS[0].sellingPrice,
      }
    ],
    subtotal: 32500,
    discountTotal: 0,
    cgst: 487.5,
    sgst: 487.5,
    igst: 0,
    taxTotal: 975,
    grandTotal: 33475,
    amountPaid: 33475,
    change: 0,
    paymentMethod: 'UPI',
    paymentDetails: { upi: 33475, upiRef: '312345678901' },
    goldRate: 6500,
    silverRate: 80,
    platinumRate: 3500,
    status: 'Completed',
    notes: '',
    createdAt: subDays(new Date(), 5).toISOString(),
    createdBy: 'Admin',
  },
  {
    id: uuidv4(),
    invoiceNumber: 'INV-2024-0002',
    customerId: 'cust-2',
    customerName: 'Vikram Malhotra',
    customerPhone: '9810056789',
    items: [
      {
        product: SEED_PRODUCTS[1],
        quantity: 1,
        discountPercent: 5,
        discountAmount: 8750,
        finalPrice: 166250,
      }
    ],
    subtotal: 175000,
    discountTotal: 8750,
    cgst: 2493.75,
    sgst: 2493.75,
    igst: 0,
    taxTotal: 4987.5,
    grandTotal: 171237.5,
    amountPaid: 171237.5,
    change: 0,
    paymentMethod: 'Card',
    paymentDetails: { card: 171237.5, cardLast4: '5566' },
    goldRate: 6480,
    silverRate: 78,
    platinumRate: 3450,
    status: 'Completed',
    notes: 'Wedding purchase.',
    createdAt: subDays(new Date(), 2).toISOString(),
    createdBy: 'Admin',
  }
];
